### ISSUE TITLE
pretty sure discord rpc being used in this way is against tos

### ISSUE THREAD

**Issue by Anthony2be** [TheUntraceable/TokenInvalidator#1]
correct me if im wrong but from what i see, it is (im not using discord cause im at school)

**Comment by TheUntraceable** [comment]
I double checked in the Discord Developers server, and I did a quick scan for "token" in their ToS, and I don't think it is. If you have any reason to disagree, let me know.
![image](https://user-images.githubusercontent.com/73362400/198382795-67cc4c36-8e2f-46bd-bab7-d7f330335111.png)
